### ISSUE TITLE
Add Ordered To-Do List Type

### ISSUE THREAD

**Issue by johneastman** [johneastman/todo#55]
Add a new list type called "Ordered To-Do Lists." These list types are the same as "To-Do Lists" but include `index + 1` before the name (e.g., `1. Dishes`). This will be useful for tasks that need to be completed in a certain order.

**Comment by Vaibob** [comment]
Hi @johneastman ,

Can I start contributing to the repository?

Thanks.

**Comment by johneastman** [comment]
@Vaibob, yes!

**Comment by johneastman** [comment]
Commit: https://github.com/johneastman/todo/commit/78bf14c096fb0e7a52ab2052809036cc55eff730
